---
driver:
  name: ec2
  driver_config:
    aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
    region: us-east-1

provisioner:
  name: chef_zero

platforms:
  - name: amazon-2014.09.01
    driver_plugin: ec2
    driver_config:
      image_id: ami-9a6ed3f2
      username: ec2-user
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>

suites:
  - name: default
    run_list:
      - recipe[oracle_jdk::default]
    attributes:
      oracle_jdk:
        accept_oracle_download_terms: true
  - name: jdks
    run_list:
      - recipe[apt::default]
      - recipe[oracle_test::jdks]
