AllCops:
  Include:
    - '**/Berksfile'
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**/*

Style/Documentation:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Metrics/AbcSize:
  Max: 16

# Metrics/MethodLength:
#   Max: 20

#inherit_from: .rubocop_todo.yml
